# Generated by Django 5.2.6 on 2025-09-25 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('duracao_min', models.PositiveIntegerField(default=30)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Procedimento (Catálogo)',
                'verbose_name_plural': 'Procedimentos (Catálogo)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RA', 'Rascunho'), ('AG', 'Aguardando aprovação'), ('AP', 'Aprovado'), ('EA', 'Em andamento'), ('CO', 'Concluído'), ('CA', 'Cancelado')], default='RA', max_length=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_tratamento', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Plano de Tratamento',
                'verbose_name_plural': 'Planos de Tratamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('validade', models.DateField()),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='tratamentos.planotratamento')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoPlanejado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente_superficie', models.CharField(blank=True, max_length=8)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('AP', 'Aprovado'), ('EX', 'Executado'), ('CA', 'Cancelado')], default='PE', max_length=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='tratamentos.planotratamento')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planejados', to='tratamentos.catalogoprocedimento')),
            ],
            options={
                'verbose_name': 'Procedimento Planejado',
                'verbose_name_plural': 'Procedimentos Planejados',
                'ordering': ['plano_id'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoExecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente', models.CharField(max_length=2)),
                ('superficie', models.CharField(blank=True, max_length=1)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('realizado_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos_executados', to='consultas.consulta')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executados', to='tratamentos.catalogoprocedimento')),
                ('planejado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes', to='tratamentos.procedimentoplanejado')),
            ],
            options={
                'verbose_name': 'Procedimento Executado',
                'verbose_name_plural': 'Procedimentos Executados',
                'ordering': ['-realizado_em'],
            },
        ),
    ]
