# Generated by Django 5.2.6 on 2025-09-27 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('pacientes', '0002_paciente_deleted_at_paciente_is_active'),
        ('tratamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planotratamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_tratamento', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='procedimentoexecutado',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos_executados', to='consultas.consulta'),
        ),
    ]
