# Generated by Django 5.2.6 on 2025-09-25 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('marca', models.CharField(blank=True, max_length=60)),
                ('lote', models.CharField(blank=True, max_length=60)),
                ('validade', models.DateField(blank=True, null=True)),
                ('qtd_minima', models.PositiveIntegerField(default=0)),
                ('qtd_atual', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=3)),
                ('quantidade', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to='consultas.consulta')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='estoque.itemestoque')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'ordering': ['-criado_em'],
            },
        ),
    ]
