# Generated by Django 5.2.6 on 2025-09-25 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TermoConsentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('caminho_assinatura', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Termo de Consentimento',
                'verbose_name_plural': 'Termos de Consentimento',
                'ordering': ['-assinado_em'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_arquivo', models.CharField(max_length=300)),
                ('tipo_arquivo', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='consultas.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EvolucaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='consultas.consulta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes_clinicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evolução Clínica',
                'verbose_name_plural': 'Evoluções Clínicas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente', models.CharField(choices=[('11', '11 - Incisivo Central Superior Direito'), ('12', '12 - Incisivo Lateral Superior Direito'), ('13', '13 - Canino Superior Direito'), ('14', '14 - 1º Pré-molar Superior Direito'), ('15', '15 - 2º Pré-molar Superior Direito'), ('16', '16 - 1º Molar Superior Direito'), ('17', '17 - 2º Molar Superior Direito'), ('18', '18 - 3º Molar Superior Direito'), ('21', '21 - Incisivo Central Superior Esquerdo'), ('22', '22 - Incisivo Lateral Superior Esquerdo'), ('23', '23 - Canino Superior Esquerdo'), ('24', '24 - 1º Pré-molar Superior Esquerdo'), ('25', '25 - 2º Pré-molar Superior Esquerdo'), ('26', '26 - 1º Molar Superior Esquerdo'), ('27', '27 - 2º Molar Superior Esquerdo'), ('28', '28 - 3º Molar Superior Esquerdo'), ('31', '31 - Incisivo Central Inferior Esquerdo'), ('32', '32 - Incisivo Lateral Inferior Esquerdo'), ('33', '33 - Canino Inferior Esquerdo'), ('34', '34 - 1º Pré-molar Inferior Esquerdo'), ('35', '35 - 2º Pré-molar Inferior Esquerdo'), ('36', '36 - 1º Molar Inferior Esquerdo'), ('37', '37 - 2º Molar Inferior Esquerdo'), ('38', '38 - 3º Molar Inferior Esquerdo'), ('41', '41 - Incisivo Central Inferior Direito'), ('42', '42 - Incisivo Lateral Inferior Direito'), ('43', '43 - Canino Inferior Direito'), ('44', '44 - 1º Pré-molar Inferior Direito'), ('45', '45 - 2º Pré-molar Inferior Direito'), ('46', '46 - 1º Molar Inferior Direito'), ('47', '47 - 2º Molar Inferior Direito'), ('48', '48 - 3º Molar Inferior Direito'), ('51', '51 - Incisivo Central Superior Direito (decíduo)'), ('52', '52 - Incisivo Lateral Superior Direito (decíduo)'), ('53', '53 - Canino Superior Direito (decíduo)'), ('54', '54 - 1º Molar Superior Direito (decíduo)'), ('55', '55 - 2º Molar Superior Direito (decíduo)'), ('61', '61 - Incisivo Central Superior Esquerdo (decíduo)'), ('62', '62 - Incisivo Lateral Superior Esquerdo (decíduo)'), ('63', '63 - Canino Superior Esquerdo (decíduo)'), ('64', '64 - 1º Molar Superior Esquerdo (decíduo)'), ('65', '65 - 2º Molar Superior Esquerdo (decíduo)'), ('71', '71 - Incisivo Central Inferior Esquerdo (decíduo)'), ('72', '72 - Incisivo Lateral Inferior Esquerdo (decíduo)'), ('73', '73 - Canino Inferior Esquerdo (decíduo)'), ('74', '74 - 1º Molar Inferior Esquerdo (decíduo)'), ('75', '75 - 2º Molar Inferior Esquerdo (decíduo)'), ('81', '81 - Incisivo Central Inferior Direito (decíduo)'), ('82', '82 - Incisivo Lateral Inferior Direito (decíduo)'), ('83', '83 - Canino Inferior Direito (decíduo)'), ('84', '84 - 1º Molar Inferior Direito (decíduo)'), ('85', '85 - 2º Molar Inferior Direito (decíduo)')], max_length=2)),
                ('superficie', models.CharField(blank=True, choices=[('M', 'Mesial'), ('D', 'Distal'), ('O', 'Oclusal'), ('I', 'Incisal'), ('V', 'Vestibular/Bucal'), ('P', 'Palatina'), ('L', 'Lingual')], max_length=1)),
                ('condicao', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
                'ordering': ['paciente', 'dente'],
            },
        ),
    ]
