# Generated by Django 5.2.6 on 2025-09-25 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('prontuario', '0001_initial'),
        ('tratamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='procedimento_executado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_odontograma', to='tratamentos.procedimentoexecutado'),
        ),
        migrations.AddField(
            model_name='receita',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='consultas.consulta'),
        ),
        migrations.AddField(
            model_name='termoconsentimento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos_consentimento', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='termoconsentimento',
            name='procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='tratamentos.catalogoprocedimento'),
        ),
    ]
