# Generated by Django 5.2.6 on 2025-09-25 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AG', 'Agendada'), ('CF', 'Confirmada'), ('EA', 'Em andamento'), ('CO', 'Concluída'), ('CA', 'Cancelada'), ('FA', 'Faltou')], default='AG', max_length=2)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('sala', models.CharField(max_length=30)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('WA', 'WhatsApp'), ('SM', 'SMS'), ('EM', 'E-mail')], max_length=2)),
                ('agendado_em', models.DateTimeField()),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AG', 'Agendado'), ('EN', 'Enviado'), ('FA', 'Falha')], default='AG', max_length=2)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='consultas.consulta')),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
                'ordering': ['-agendado_em'],
            },
        ),
    ]
