# Generated by Django 5.2.6 on 2025-09-25 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(blank=True, max_length=60)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('PA', 'Parcial'), ('PG', 'Paga'), ('CA', 'Cancelada')], default='AB', max_length=2)),
                ('numero_nfse', models.CharField(blank=True, max_length=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento', models.CharField(choices=[('PX', 'PIX'), ('CC', 'Cartão'), ('DN', 'Dinheiro'), ('BL', 'Boleto')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_em', models.DateTimeField(auto_now_add=True)),
                ('parcela', models.PositiveIntegerField(default=1)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.fatura')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-pago_em'],
            },
        ),
    ]
